#https://github.com/jfrog/charts/blob/master/stable/artifactory/values-large.yaml
artifactory:
  artifactory:
    replicaCount: 2
    resources:
      requests:
        memory: "6Gi"
        cpu: "4"
      limits:
        memory: "10Gi"
        cpu: "8"
    javaOpts:
      xms: "6g"
      xmx: "8g"