#You can create a secret using the below command and connect to the external DB configured for Xray
#kubectl create secret generic xray-database-creds \
#--from-literal=db-user=XRAY_DATABASE_USER \
#--from-literal=db-password=XRAY_DATABASE_PASSWORD \
#--from-literal=db-url=postgres://$DB_SERVER:5432/$XRAY_DB?sslmode=disable -n $MY_NAMESPACE

xray:
  enabled: true
  replicaCount: 2
  database:
    type: postgresql
    driver: org.postgresql.Driver
    secrets:
      user:
        name: xray-database-creds
        key: db-user
      password:
        name: xray-database-creds
        key: db-password
      url:
        name: xray-database-creds
        key: db-url
  common:
    persistence:
      # 400Gi seems to be the minimum since JAS
      size: 500Gi
  server:
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "10Gi"
        cpu: "10"

  analysis:
    resources:
      requests:
        memory: "300Mi"
        cpu: "50m"
      limits:
        memory: "10Gi"
        cpu: "10"

  persist:
    resources:
      requests:
        memory: "300Mi"
        cpu: "50m"
      limits:
        memory: "10Gi"
        cpu: "10"

  indexer:
    resources:
      requests:
        memory: "300Mi"
        cpu: "50m"
      limits:
        memory: "10Gi"
        cpu: "10"